In [4]:
import numpy as np

1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado`altura_em_centimetro` transformando a lista`lista_de_alturas` em um ndarray do numpy com a função `np.arra() 
ii. Crie um outro objeto ``altura_em_metr``, com os valores d``altura_em_centimetr ` convertidos para metros.

In [19]:
lista_de_centimetros = list(range(170, 190, 5))
lista_de_centimetros

[170, 175, 180, 185]

In [20]:
lista_de_centimetros = list(range(170, 190, 5))

# i. Transformar a lista em um ndarray
altura_em_centimetros = np.array(lista_de_centimetros)

# ii. Converter os valores de centímetros para metros
altura_em_metros = altura_em_centimetros / 100

print("Altura em centímetros:", altura_em_centimetros)
print("Altura em metros:", altura_em_metros)

Altura em centímetros: [170 175 180 185]
Altura em metros: [1.7  1.75 1.8  1.85]


2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos`lista_pesos = [70, 75, 80, 85`. Crie um*ndarra* chamado`peso  com a função`np.array(` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamad``i``.

In [11]:
lista_pesos = [70, 75, 80, 85]
lista_alturas = [1.75, 1.80, 1.65, 1.70]

# Criando o ndarray para pesos
pesos = np.array(lista_pesos)

# Supondo as alturas em metros
alturas = np.array(lista_alturas)

# Calculando o IMC
imc = pesos / (alturas ** 2)
imc


array([22.85714286, 23.14814815, 29.38475666, 29.41176471])

3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [12]:
# Lista de dados financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],
                     [1000, 2500, 3000, 5000],
                     [6000, 5500, 7000, 16000]]

# Transformando em ndarray
nd_financeiros = np.array(dados_financeiros)
print(nd_financeiros)

[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]


In [13]:
# Transpor o ndarray para que as informações fiquem como linhas de indivíduos e colunas de dados
nd_financeiros_transposto = nd_financeiros.transpose()

# Imprimir a segunda linha
print("Segunda linha:", nd_financeiros_transposto[1])

# Imprimir a segunda coluna
print("Segunda coluna:", nd_financeiros_transposto[:, 1])


Segunda linha: [2500 2500 5500]
Segunda coluna: [1000 2500 3000 5000]


In [14]:
# Extraindo as colunas
custo_fixo = nd_financeiros_transposto[:, 0]
divida_financeira = nd_financeiros_transposto[:, 1]
renda_familiar = nd_financeiros_transposto[:, 2]

# Calculando o endividamento total
endividamento_total = (custo_fixo + divida_financeira) / renda_familiar
print("Endividamento total:", endividamento_total)


Endividamento total: [0.66666667 0.90909091 0.57142857 0.9375    ]


In [15]:
# Corrigindo o valor de renda familiar do terceiro indivíduo
nd_financeiros_transposto[2, 2] = 10000  # Índice 2 é a terceira pessoa e a coluna de renda é a de índice 2

# Refazendo o cálculo do endividamento total
renda_familiar_corrigida = nd_financeiros_transposto[:, 2]
endividamento_total_corrigido = (custo_fixo + divida_financeira) / renda_familiar_corrigida
print("Endividamento total corrigido:", endividamento_total_corrigido)


Endividamento total corrigido: [0.66666667 0.90909091 0.4        0.9375    ]


4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [16]:
# Gerar os números pseudo-aleatórios
np.random.seed(1234)
poi = np.random.poisson(3, 100)

# Criar o objeto bool_zero
bool_zero = (poi == 0)
print(bool_zero)

[False False False False False False False False False  True False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False  True False False False False False False False False False False
 False False False False]


In [17]:
# Contar a quantidade de zeros
qtd_zeros = sum(bool_zero)
print("Quantidade de zeros:", qtd_zeros)

Quantidade de zeros: 6


In [18]:
# Selecionar os valores de poi que não são zero
poi_nao_zero = poi[~bool_zero] 
print("Valores diferentes de zero:", poi_nao_zero)

Valores diferentes de zero: [3 3 6 2 4 5 4 4 2 3 3 2 8 2 3 3 3 4 4 2 6 6 3 4 3 5 2 1 3 2 2 3 2 4 4 5 7
 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4 1 1 7 1
 2 1 3 7 4 4 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
